Revert "Add push secret for kafka user"
This reverts commit 61c0bc5c4695fc33987c9ef564c838b6c2d2e818.

diff --git a/common/Makefile b/common/Makefile
--- a/common/Makefile
+++ b/common/Makefile
@@ -130,17 +130,17 @@ token-kubeconfig: ## Create a local ~/.kube/config with password (not usually ne
 .PHONY: validate-origin
 validate-origin: ## verify the git origin is available
 	@echo "Checking repository:"
-	# $(eval UPSTREAMURL := $(shell yq -r '.main.git.repoUpstreamURL // (.main.git.repoUpstreamURL = "")' values-global.yaml))
-	# @if [ -z "$(UPSTREAMURL)" ]; then\
-	# 	echo -n "  $(TARGET_REPO) - branch '$(TARGET_BRANCH)': ";\
-	# 	git ls-remote --exit-code --heads $(TARGET_REPO) $(TARGET_BRANCH) >/dev/null &&\
-	# 		echo "OK" || (echo "NOT FOUND"; exit 1);\
-	# else\
-	# 	echo "Upstream URL set to: $(UPSTREAMURL)";\
-	# 	echo -n "  $(UPSTREAMURL) - branch '$(TARGET_BRANCH)': ";\
-	# 	git ls-remote --exit-code --heads $(UPSTREAMURL) $(TARGET_BRANCH) >/dev/null &&\
-	# 		echo "OK" || (echo "NOT FOUND"; exit 1);\
-	# fi
+	$(eval UPSTREAMURL := $(shell yq -r '.main.git.repoUpstreamURL // (.main.git.repoUpstreamURL = "")' values-global.yaml))
+	@if [ -z "$(UPSTREAMURL)" ]; then\
+		echo -n "  $(TARGET_REPO) - branch '$(TARGET_BRANCH)': ";\
+		git ls-remote --exit-code --heads $(TARGET_REPO) $(TARGET_BRANCH) >/dev/null &&\
+			echo "OK" || (echo "NOT FOUND"; exit 1);\
+	else\
+		echo "Upstream URL set to: $(UPSTREAMURL)";\
+		echo -n "  $(UPSTREAMURL) - branch '$(TARGET_BRANCH)': ";\
+		git ls-remote --exit-code --heads $(UPSTREAMURL) $(TARGET_BRANCH) >/dev/null &&\
+			echo "OK" || (echo "NOT FOUND"; exit 1);\
+	fi
 
 .PHONY: validate-cluster
 validate-cluster: ## Do some cluster validations before installing
